/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as FulfillmentRouteImport } from './routes/fulfillment'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminManufacturersRouteImport } from './routes/admin.manufacturers'
import { Route as AdminLaunchRouteImport } from './routes/admin.launch'
import { Route as AdminFlashSaleRouteImport } from './routes/admin.flash-sale'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCjSyncRouteImport } from './routes/admin.cj-sync'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as ApiWebhooksShippingRouteImport } from './routes/api.webhooks.shipping'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const FulfillmentRoute = FulfillmentRouteImport.update({
  id: '/fulfillment',
  path: '/fulfillment',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManufacturersRoute = AdminManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaunchRoute = AdminLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlashSaleRoute = AdminFlashSaleRouteImport.update({
  id: '/flash-sale',
  path: '/flash-sale',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCjSyncRoute = AdminCjSyncRouteImport.update({
  id: '/cj-sync',
  path: '/cj-sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksShippingRoute = ApiWebhooksShippingRouteImport.update({
  id: '/api/webhooks/shipping',
  path: '/api/webhooks/shipping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/fulfillment': typeof FulfillmentRoute
  '/grievance': typeof GrievanceRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/staff': typeof StaffRouteWithChildren
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cj-sync': typeof AdminCjSyncRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/flash-sale': typeof AdminFlashSaleRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/manufacturers': typeof AdminManufacturersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/webhooks/shipping': typeof ApiWebhooksShippingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/fulfillment': typeof FulfillmentRoute
  '/grievance': typeof GrievanceRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cj-sync': typeof AdminCjSyncRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/flash-sale': typeof AdminFlashSaleRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/manufacturers': typeof AdminManufacturersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/webhooks/shipping': typeof ApiWebhooksShippingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/fulfillment': typeof FulfillmentRoute
  '/grievance': typeof GrievanceRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/staff': typeof StaffRouteWithChildren
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cj-sync': typeof AdminCjSyncRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/flash-sale': typeof AdminFlashSaleRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/manufacturers': typeof AdminManufacturersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/webhooks/shipping': typeof ApiWebhooksShippingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/disclaimer'
    | '/faq'
    | '/fulfillment'
    | '/grievance'
    | '/login'
    | '/partner'
    | '/privacy'
    | '/refund'
    | '/search'
    | '/shipping'
    | '/staff'
    | '/terms'
    | '/warranty'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/cj-sync'
    | '/admin/coupons'
    | '/admin/flash-sale'
    | '/admin/launch'
    | '/admin/manufacturers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/staff'
    | '/admin/users'
    | '/category/$category'
    | '/orders/$orderId'
    | '/product/$slug'
    | '/admin/'
    | '/orders/'
    | '/staff/'
    | '/api/webhooks/shipping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/disclaimer'
    | '/faq'
    | '/fulfillment'
    | '/grievance'
    | '/login'
    | '/partner'
    | '/privacy'
    | '/refund'
    | '/search'
    | '/shipping'
    | '/terms'
    | '/warranty'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/cj-sync'
    | '/admin/coupons'
    | '/admin/flash-sale'
    | '/admin/launch'
    | '/admin/manufacturers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/staff'
    | '/admin/users'
    | '/category/$category'
    | '/orders/$orderId'
    | '/product/$slug'
    | '/admin'
    | '/orders'
    | '/staff'
    | '/api/webhooks/shipping'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/deals'
    | '/disclaimer'
    | '/faq'
    | '/fulfillment'
    | '/grievance'
    | '/login'
    | '/partner'
    | '/privacy'
    | '/refund'
    | '/search'
    | '/shipping'
    | '/staff'
    | '/terms'
    | '/warranty'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/cj-sync'
    | '/admin/coupons'
    | '/admin/flash-sale'
    | '/admin/launch'
    | '/admin/manufacturers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/staff'
    | '/admin/users'
    | '/category/$category'
    | '/orders/$orderId'
    | '/product/$slug'
    | '/admin/'
    | '/orders/'
    | '/staff/'
    | '/api/webhooks/shipping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  FulfillmentRoute: typeof FulfillmentRoute
  GrievanceRoute: typeof GrievanceRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  StaffRoute: typeof StaffRouteWithChildren
  TermsRoute: typeof TermsRoute
  WarrantyRoute: typeof WarrantyRoute
  WishlistRoute: typeof WishlistRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiWebhooksShippingRoute: typeof ApiWebhooksShippingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfillment': {
      id: '/fulfillment'
      path: '/fulfillment'
      fullPath: '/fulfillment'
      preLoaderRoute: typeof FulfillmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manufacturers': {
      id: '/admin/manufacturers'
      path: '/manufacturers'
      fullPath: '/admin/manufacturers'
      preLoaderRoute: typeof AdminManufacturersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/launch': {
      id: '/admin/launch'
      path: '/launch'
      fullPath: '/admin/launch'
      preLoaderRoute: typeof AdminLaunchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flash-sale': {
      id: '/admin/flash-sale'
      path: '/flash-sale'
      fullPath: '/admin/flash-sale'
      preLoaderRoute: typeof AdminFlashSaleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cj-sync': {
      id: '/admin/cj-sync'
      path: '/cj-sync'
      fullPath: '/admin/cj-sync'
      preLoaderRoute: typeof AdminCjSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/shipping': {
      id: '/api/webhooks/shipping'
      path: '/api/webhooks/shipping'
      fullPath: '/api/webhooks/shipping'
      preLoaderRoute: typeof ApiWebhooksShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCjSyncRoute: typeof AdminCjSyncRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminFlashSaleRoute: typeof AdminFlashSaleRoute
  AdminLaunchRoute: typeof AdminLaunchRoute
  AdminManufacturersRoute: typeof AdminManufacturersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCjSyncRoute: AdminCjSyncRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminFlashSaleRoute: AdminFlashSaleRoute,
  AdminLaunchRoute: AdminLaunchRoute,
  AdminManufacturersRoute: AdminManufacturersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffRouteChildren {
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  FulfillmentRoute: FulfillmentRoute,
  GrievanceRoute: GrievanceRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  StaffRoute: StaffRouteWithChildren,
  TermsRoute: TermsRoute,
  WarrantyRoute: WarrantyRoute,
  WishlistRoute: WishlistRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiWebhooksShippingRoute: ApiWebhooksShippingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
